# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = CarouselImageWindow
DESTDIR = ../x64/Debug
QT += core gui widgets
CONFIG += debug

include(CarouselImageWindow.pri)
